name: pyLint

on:
  push:
  workflow_dispatch:

jobs:
  pyLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for showstoppers
        run: autopep8 --verbose --in-place --recursive --aggressive --aggressive --max-line-length 99 .
      - name: Remove unused imports and variables
        run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
      - name: lint with isort and black
        run: |
          isort .
          black --fast .
      - name: Commit Checkout
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_user_name: Achu2234
          commit_user_email: 77989182+Achu2234@users.noreply.github.com
          commit_options: '--no-verify'
          commit_message: 'pyLint: auto fixes'
          commit_author: Achu2234 <77989182+AsmSafone@users.noreply.github.com>

